fix: roles/ceph-common & roles/ceph-deploy

diff --git a/roles/ceph-common/tasks/main.yml b/roles/ceph-common/tasks/main.yml
--- a/roles/ceph-common/tasks/main.yml
+++ b/roles/ceph-common/tasks/main.yml
@@ -13,9 +13,8 @@
 
 - name: Copy SSH key to each host if not already installed
   ansible.builtin.shell: |
-    ssh-copy-id -i {{ ssh_key }}.pub -o StrictHostKeyChecking=no {{ ssh_user }}@{{ item }} \
-    echo "SSH key copied successfully to {{ item }}." || \
-    echo "Failed to copy SSH key to {{ item }}."
+    ssh-copy-id -i {{ ssh_key }}.pub -o StrictHostKeyChecking=no {{ ssh_user }}@{{ item }} && \
+    (echo "SSH key copied successfully to {{ item }}." || echo "Failed to copy SSH key to {{ item }}.")
   loop: "{{ groups['clients'] }}"
   loop_control:
     loop_var: item
diff --git a/roles/ceph-deploy/tasks/add_host_and_label.yml b/roles/ceph-deploy/tasks/add_host_and_label.yml
--- a/roles/ceph-deploy/tasks/add_host_and_label.yml
+++ b/roles/ceph-deploy/tasks/add_host_and_label.yml
@@ -1,9 +1,8 @@
 ---
 - name: Copy SSH public key to each client host
   ansible.builtin.shell: |
-    ssh-copy-id -f -i /etc/ceph/ceph.pub {{ ssh_user }}@{{ item }} \
-    echo "SSH key copied successfully to {{ item }}." || \
-    echo "Failed to copy SSH key to {{ item }}."
+    ssh-copy-id -f -i /etc/ceph/ceph.pub -o StrictHostKeyChecking=no {{ ssh_user }}@{{ item }} && \
+    (echo "SSH key copied successfully to {{ item }}." || echo "Failed to copy SSH key to {{ item }}.")
   loop: "{{ groups['clients'] }}"
   loop_control:
     loop_var: item
